name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar notebooks
        run: |
          jupyter nbconvert --to notebook --execute notebooks/ArbolDecision.ipynb
          jupyter nbconvert --to notebook --execute notebooks/KNN.ipynb
          jupyter nbconvert --to notebook --execute notebooks/RegresionLineal.ipynb


